import os
print('Start experiments of Table 2 Tool Devign.')
print('Notice that Devign has randomness when predicting results. The results may be a little bit different from the one shown in the paper.')
print('Please mainly focus on F1 scores and the relationships between different columns.\n')

print('Running Table 2 - Devign - Reproduction - Baseline')
print('This may take 20 min')
os.system('bash devign_non_vulgen_reveal.sh')
f=open('devign_non_vulgen_reveal.out')
lines=f.readlines()
print('Accuracy:          Precision:        Recall:           F1:')
print(lines[-1][16:])

print('Running Table 2 - Devign - Reproduction - Synthetic')
print('This may take 20 min')
os.system('bash devign_vulgen_syn_reveal.sh')
f=open('devign_vulgen_syn_reveal.out')
lines=f.readlines()
print('Accuracy:          Precision:        Recall:           F1:')
print(lines[-1][16:])

print('Running Table 2 - Devign - Reproduction - Generated')
print('This may take 20 min')
os.system('bash devign_vulgen_reveal.sh')
f=open('devign_vulgen_reveal.out')
lines=f.readlines()
print('Accuracy:          Precision:        Recall:           F1:')
print(lines[-1][16:])


print('Running Table 2 - Devign - Reproduction - Ground Truth')
print('This may take 20 min')
os.system('bash devign_vulgen_gth_reveal.sh')
f=open('devign_vulgen_gth_reveal.out')
lines=f.readlines()
print('Accuracy:          Precision:        Recall:           F1:')
print(lines[-1][16:])


print('Running Table 2 - Devign - Reproduction - Wild')
print('This may take 20 min')
os.system('bash devign_wild_reveal.sh')
f=open('devign_wild_reveal.out')
lines=f.readlines()
print('Accuracy:          Precision:        Recall:           F1:')
print(lines[-1][16:])


print('Running Table 2 - Devign - Replication - Baseline')
print('This may take 20 min')
os.system('bash devign_non_vulgen_xen.sh')
f=open('devign_non_vulgen_xen.out')
lines=f.readlines()
print('Accuracy:          Precision:        Recall:           F1:')
print(lines[-2][16:])

print('Running Table 2 - Devign - Replication - Synthetic')
print('This may take 20 min')
os.system('bash devign_vulgen_syn_xen.sh')
f=open('devign_vulgen_syn_xen.out')
lines=f.readlines()
print('Accuracy:          Precision:        Recall:           F1:')
print(lines[-2][16:])

print('Running Table 2 - Devign - Replication - Generated')
print('This may take 20 min')
os.system('bash devign_vulgen_xen.sh')
f=open('devign_vulgen_xen.out')
lines=f.readlines()
print('Accuracy:          Precision:        Recall:           F1:')
print(lines[-2][16:])


print('Running Table 2 - Devign - Replication - Ground Truth')
print('This may take 20 min')
os.system('bash devign_vulgen_gth_xen.sh')
f=open('devign_vulgen_gth_xen.out')
lines=f.readlines()
print('Accuracy:          Precision:        Recall:           F1:')
print(lines[-2][16:])


print('Running Table 2 - Devign - Replication - Wild')
print('This may take 20 min')
os.system('bash devign_wild_xen.sh')
f=open('devign_wild_xen.out')
lines=f.readlines()
print('Accuracy:          Precision:        Recall:           F1:')
print(lines[-2][16:])
